apiVersion: apps/v1
kind: Deployment
metadata:
 name: flask-hello-deployment

spec:
 template:
   metadata:
     name: flask-hello
     labels:
       app: flask-hello
       tier: frontend
   spec:
     containers:
       - name: flask-hello
         image: safiyenur/flask-hello-world-devops-project

 replicas: 3
 selector:
   matchLabels:
     app: flask-hello
     tier: frontend
